name: build

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        name: [vim-v82-x64]
        include:
          - name: vim-v82-x64
            os: ubuntu-latest
            vim_version: 8.2.0037
            glibc_version: 2.15
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          python-version: '12.x'
      - name: Download vim
        shell: bash
        run: |
          mkdir -p ~/vim/bin
          curl -L https://github.com/vim/vim-appimage/releases/download/v${{matrix.vim_version}}/GVim-v${{matrix.vim_version}}.glibc${{matrix.glibc_version}}-x86_64.AppImage -o ~/vim/bin/vim
          chmod u+x ~/vim/bin/vim
      - name: Download test runner
        shell: bash
        run: |
          git clone --depth 1 --single-branch https://github.com/junegunn/vader.vim.git ./tests/vader.vim
          make install

      - name: Run tests
        shell: bash
        run: |
          export PATH=~/vim/bin:$PATH
          cd ./tests
          vim -u vimrc -c 'Vader! *.vader'
